backend:
  name: github
  repo: beguelins-net/beguelins.net
  branch: main
  base_url: https://sveltia-cms-auth.beguelins.workers.dev

media_folder: "static/img"  # Folder where user uploaded files should go
public_folder: "/img"
site_url: "https://dev.beguelins.net"

collections:  # A list of collections the CMS should be able to edit
  - name: "posts"  # Used in routes, i.e.: /admin/collections/:slug/edit
    label: "Posts"  # Used in the UI, i.e.: "New Post"
    folder: "content/posts"  # The path to the folder where the documents are stored
    path: "{{fields.category}}/{{slug}}"  # Each document is inside a category folder with the slug name.
    nested:
      depth: 2
      summary: "{{title}}"
    view_groups:
      - { label: "Category", field: "category" }
    create: true  # Allow users to create new documents in this collection
    fields:  # The fields each document in this collection has
      - { label: "Title", name: "title", widget: "string" }
      - label: "Category"
        name: "category"
        widget: "select"
        options:
          - { label: "Circuler au village", value: "circuler-au-village" }
          - { label: "Église et vie paroissiale", value: "eglise-et-vie-paroissiale" }
          - { label: "Exposition", value: "exposition" }
          - { label: "Histoire", value: "histoire" }
          - { label: "Histoire d'énergie", value: "histoire-d-energie" }
          - { label: "La vie agricole", value: "la-vie-agricole" }
          - { label: "La vie de l’association", value: "la-vie-de-l-association" }
          - { label: "La vie du village", value: "la-vie-du-village" }
          - { label: "Le village et son patrimoine", value: "le-village-et-son-patrimoine" }
        default: la-vie-de-l-association
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "home"
    label: "Accueil"
    files:
      - file: "content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Image", name: "image", widget: "image", required: false }
          - { label: "Body", name: "body", widget: "markdown" }
